### ISSUE TITLE
Run processes errors...

### ISSUE THREAD

**Issue by Brendanfruition** [mahalsnz/soilmoisture#199] opened 2020-10-28 00:53 UTC
Hi Byron,
Running processes this afternoon came up with a few errors.

Load Rain
![image](https://user-images.githubusercontent.com/50975792/97377195-4a3d9900-1924-11eb-8f7c-eb0ba4b188d5.png)
Run daily water use
![image](https://user-images.githubusercontent.com/50975792/97377283-8a9d1700-1924-11eb-89a0-59ddc24f7295.png)
Process rain
![image](https://user-images.githubusercontent.com/50975792/97377324-a2749b00-1924-11eb-9b26-8c11706f3b65.png)

Suggestions?? I will take a look at KC data to make sure it is entered ok.

Cheers

**Comment by Brendanfruition** [comment] 2020-10-28 03:04
Have sorted KC error, was missing a date range for citrus.

**Comment by mabbettbyron** [comment] 2020-10-28 21:46
I know sometimes the rainfall is coming through as dashes or dots not numbers. I think the hortplus guys them. Will try and at least enter none and keep going i that process.

**Comment by mabbettbyron** [comment] 2020-10-29 18:39
Should be fixed now. I have fixed on production and run load-rainfall successfully so should be all up to date.

Have asked hortplus what dashes mean?

**Comment by Brendanfruition** [comment] 2020-11-01 20:08
Hi Byron,

Still same errors coming through.

Load rainfall from Hortplus
![image](https://user-images.githubusercontent.com/50975792/97813121-f7c8f780-1cea-11eb-8ddd-1dfa2b05318c.png)

Run process rain and irrigation
![image](https://user-images.githubusercontent.com/50975792/97813096-d8ca6580-1cea-11eb-8bf8-912a60cf599a.png)

**Comment by mabbettbyron** [comment] 2020-11-03 19:33
load-rainfall is fixed (my mistake)

processrain problem again caused by meter reading with no counts. I think I'll trap these errrors. For Citrus I have deleted that meter reading record.
![image](https://user-images.githubusercontent.com/47704202/98031926-18728800-1e78-11eb-905c-41bca88c87e6.png)
![image](https://user-images.githubusercontent.com/47704202/98031963-29bb9480-1e78-11eb-9f4b-1fc49a6d6424.png)

**Comment by mabbettbyron** [comment] 2020-11-05 19:41
processrain now trapping no serial number reading records.

**Closed** 2020-11-05 20:12 UTC
Labels: bug
